language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r SpringBoot-AWS *
  - mkdir -p deploy
  - mv SpringBoot-AWS.zip deploy/SpringBoot-AWS.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ib07441-spring-boot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ib07441-spring-boot-build
    key: SpringBoot-AWS.zip
    bundle_type: zip
    application: IB07441-CodeDeploy-App-Spring-Boot
    deployment_group: IB07441-Codedeploy-DeploymentGroup-SpringBoot
    region: ap-northeast-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
      - cshyun7015@gmail.com